import type { Metadata } from "next";
import "./../globals.css";
import Sidebar from "../_components/Sidebar";
import RouteProtected from "../_components/RouteProtected";

export const metadata: Metadata = {
  title: "Admin Page",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <RouteProtected>
      <div className="flex w-full">
        <Sidebar />
        {children}
      </div>
    </RouteProtected>
  );
}
